server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:orders
    username: Yevhen
    password: mysecretpassword
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    ua.ithillel.lesson32.homework: info
    org.springframework.web: info
  file:
    path: logs/